// <auto-generated />
using System;
using CorporateAssetManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorporateAssetManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231185816_LinkApplicationUserToEmployee")]
    partial class LinkApplicationUserToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorporateAssetManager.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Asset", b =>
                {
                    b.Property<long>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssetId"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("AssetTypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CurrentAssignedEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CurrentLocationId")
                        .HasColumnType("bigint");

                    b.Property<short>("CurrentStatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WarrantyExpiration")
                        .HasColumnType("datetime2");

                    b.HasKey("AssetId");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CurrentAssignedEmployeeId");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("CurrentStatusId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetAssignmentHistory", b =>
                {
                    b.Property<long>("AssetAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssetAssignmentId"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AssignedByEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConditionOnReturn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("FromEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FromLocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ToEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ToLocationId")
                        .HasColumnType("bigint");

                    b.HasKey("AssetAssignmentId");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedByEmployeeId");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ToEmployeeId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("AssetAssignmentHistories");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetMaintenanceRecord", b =>
                {
                    b.Property<long>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaintenanceId"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ReportedByEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TechnicianEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VendorId")
                        .HasColumnType("bigint");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ReportedByEmployeeId");

                    b.HasIndex("TechnicianEmployeeId");

                    b.HasIndex("TicketId");

                    b.HasIndex("VendorId");

                    b.ToTable("AssetMaintenanceRecords");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetStatusHistory", b =>
                {
                    b.Property<long>("AssetStatusHistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssetStatusHistId"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<short?>("AssetStatusLookupStatusId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ChangedByEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<short>("NewStatusId")
                        .HasColumnType("smallint");

                    b.Property<short?>("OldStatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AssetStatusHistId");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetStatusLookupStatusId");

                    b.HasIndex("ChangedByEmployeeId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.ToTable("AssetStatusHistories");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetStatusLookup", b =>
                {
                    b.Property<short>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("AssetStatuses");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetType", b =>
                {
                    b.Property<short>("AssetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("AssetTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AssetTypeId");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("HodEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HodEmployeeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("HiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsItAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<short>("ModalityId")
                        .HasColumnType("smallint");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TerminatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("ModalityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.EmploymentStatus", b =>
                {
                    b.Property<short>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StatusId");

                    b.ToTable("EmploymentStatuses");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.HardwareSpec", b =>
                {
                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<short?>("CpuCores")
                        .HasColumnType("smallint");

                    b.Property<string>("CpuModel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GpuModel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("GpuVramMb")
                        .HasColumnType("int");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Os")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short?>("RamGb")
                        .HasColumnType("smallint");

                    b.Property<int?>("StorageGb")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.ToTable("HardwareSpecs");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.LicenseAssignment", b =>
                {
                    b.Property<long>("LicenseAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LicenseAssignmentId"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("LicenseId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SeatsUsed")
                        .HasColumnType("int");

                    b.HasKey("LicenseAssignmentId");

                    b.HasIndex("AssetId");

                    b.HasIndex("LicenseId");

                    b.ToTable("LicenseAssignments");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LocationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<short>("LocationTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.LocationType", b =>
                {
                    b.Property<short>("LocationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("LocationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationTypeId");

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Modality", b =>
                {
                    b.Property<short>("ModalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ModalityId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ModalityId");

                    b.ToTable("Modalities");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.PurchaseOrder", b =>
                {
                    b.Property<long>("PoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PoId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ApprovedByEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint");

                    b.HasKey("PoId");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.SoftwareLicense", b =>
                {
                    b.Property<long>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LicenseId"));

                    b.Property<long?>("AssignedAssetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AssignedEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchasedFrom")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Seats")
                        .HasColumnType("int");

                    b.HasKey("LicenseId");

                    b.HasIndex("AssignedAssetId");

                    b.HasIndex("AssignedEmployeeId");

                    b.ToTable("SoftwareLicenses");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketId"));

                    b.Property<long?>("AssignedToEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<long?>("RelatedAssetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SlaDueAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<short>("TicketTypeId")
                        .HasColumnType("smallint");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedToEmployeeId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RelatedAssetId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketApproval", b =>
                {
                    b.Property<long>("TicketApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketApprovalId"));

                    b.Property<long>("ApproverEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ApproverRole")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketApprovalId");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketApprovals");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketComment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentId"));

                    b.Property<long>("AuthorEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Internal")
                        .HasColumnType("bit");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentId");

                    b.HasIndex("AuthorEmployeeId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketStatus", b =>
                {
                    b.Property<short>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("TicketStatuses");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketType", b =>
                {
                    b.Property<short>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("TypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Vendor", b =>
                {
                    b.Property<long>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VendorId"));

                    b.Property<string>("Contact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CorporateAssetManager.Models.ApplicationUser", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Employee", "Employee")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("CorporateAssetManager.Models.ApplicationUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Asset", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Employee", "CurrentAssignedEmployee")
                        .WithMany("AssetsAssigned")
                        .HasForeignKey("CurrentAssignedEmployeeId");

                    b.HasOne("CorporateAssetManager.Models.Location", "CurrentLocation")
                        .WithMany("Assets")
                        .HasForeignKey("CurrentLocationId");

                    b.HasOne("CorporateAssetManager.Models.AssetStatusLookup", "CurrentStatus")
                        .WithMany("Assets")
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("CurrentAssignedEmployee");

                    b.Navigation("CurrentLocation");

                    b.Navigation("CurrentStatus");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetAssignment", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetAssignmentHistory", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Asset", "Asset")
                        .WithMany("AssetAssignmentHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Employee", "AssignedByEmployee")
                        .WithMany("AssetAssignmentHistoriesAssignedBy")
                        .HasForeignKey("AssignedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Employee", "FromEmployee")
                        .WithMany("AssetAssignmentHistoriesFrom")
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Location", "FromLocation")
                        .WithMany("AssetAssignmentHistoriesFrom")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Employee", "ToEmployee")
                        .WithMany("AssetAssignmentHistoriesTo")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Location", "ToLocation")
                        .WithMany("AssetAssignmentHistoriesTo")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("FromEmployee");

                    b.Navigation("FromLocation");

                    b.Navigation("ToEmployee");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetMaintenanceRecord", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Asset", "Asset")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Employee", "ReportedByEmployee")
                        .WithMany("MaintenanceRecordsReported")
                        .HasForeignKey("ReportedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Employee", "TechnicianEmployee")
                        .WithMany("MaintenanceRecordsTechnician")
                        .HasForeignKey("TechnicianEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Ticket", "Ticket")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("TicketId");

                    b.HasOne("CorporateAssetManager.Models.Vendor", "Vendor")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VendorId");

                    b.Navigation("Asset");

                    b.Navigation("ReportedByEmployee");

                    b.Navigation("TechnicianEmployee");

                    b.Navigation("Ticket");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetStatusHistory", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Asset", "Asset")
                        .WithMany("AssetStatusHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.AssetStatusLookup", null)
                        .WithMany("AssetStatusHistories")
                        .HasForeignKey("AssetStatusLookupStatusId");

                    b.HasOne("CorporateAssetManager.Models.Employee", "ChangedByEmployee")
                        .WithMany("AssetStatusHistories")
                        .HasForeignKey("ChangedByEmployeeId");

                    b.HasOne("CorporateAssetManager.Models.AssetStatusLookup", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.AssetStatusLookup", "OldStatus")
                        .WithMany()
                        .HasForeignKey("OldStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Department", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Employee", "HeadOfDepartment")
                        .WithMany("DepartmentsAsHead")
                        .HasForeignKey("HodEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Location", "Location")
                        .WithMany("Departments")
                        .HasForeignKey("LocationId");

                    b.Navigation("HeadOfDepartment");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Employee", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("CorporateAssetManager.Models.Modality", "Modality")
                        .WithMany("Employees")
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.EmploymentStatus", "EmploymentStatus")
                        .WithMany("Employees")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Employee", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Department");

                    b.Navigation("EmploymentStatus");

                    b.Navigation("Modality");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.HardwareSpec", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Asset", "Asset")
                        .WithOne("HardwareSpec")
                        .HasForeignKey("CorporateAssetManager.Models.HardwareSpec", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.LicenseAssignment", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Asset", "Asset")
                        .WithMany("LicenseAssignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.SoftwareLicense", "License")
                        .WithMany("LicenseAssignments")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("License");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Location", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("CorporateAssetManager.Models.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.PurchaseOrder", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Employee", "ApprovedByEmployee")
                        .WithMany("PurchaseOrdersApproved")
                        .HasForeignKey("ApprovedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Employee", "CreatedByEmployee")
                        .WithMany("PurchaseOrdersCreated")
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.SoftwareLicense", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Asset", "AssignedAsset")
                        .WithMany("SoftwareLicenses")
                        .HasForeignKey("AssignedAssetId");

                    b.HasOne("CorporateAssetManager.Models.Employee", "AssignedEmployee")
                        .WithMany("SoftwareLicensesAssigned")
                        .HasForeignKey("AssignedEmployeeId");

                    b.Navigation("AssignedAsset");

                    b.Navigation("AssignedEmployee");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Ticket", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Employee", "AssignedToEmployee")
                        .WithMany("TicketsAssigned")
                        .HasForeignKey("AssignedToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorporateAssetManager.Models.Employee", "CreatedByEmployee")
                        .WithMany("TicketsCreated")
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Department", "Department")
                        .WithMany("Tickets")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("CorporateAssetManager.Models.Asset", "RelatedAsset")
                        .WithMany("Tickets")
                        .HasForeignKey("RelatedAssetId");

                    b.HasOne("CorporateAssetManager.Models.TicketStatus", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToEmployee");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Department");

                    b.Navigation("RelatedAsset");

                    b.Navigation("Status");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketApproval", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Employee", "ApproverEmployee")
                        .WithMany("TicketApprovals")
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Ticket", "Ticket")
                        .WithMany("TicketApprovals")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverEmployee");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketComment", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.Employee", "AuthorEmployee")
                        .WithMany("TicketComments")
                        .HasForeignKey("AuthorEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.Ticket", "Ticket")
                        .WithMany("TicketComments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorEmployee");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateAssetManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CorporateAssetManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Asset", b =>
                {
                    b.Navigation("AssetAssignmentHistories");

                    b.Navigation("AssetStatusHistories");

                    b.Navigation("HardwareSpec");

                    b.Navigation("LicenseAssignments");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("SoftwareLicenses");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetStatusLookup", b =>
                {
                    b.Navigation("AssetStatusHistories");

                    b.Navigation("Assets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Employee", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("AssetAssignmentHistoriesAssignedBy");

                    b.Navigation("AssetAssignmentHistoriesFrom");

                    b.Navigation("AssetAssignmentHistoriesTo");

                    b.Navigation("AssetStatusHistories");

                    b.Navigation("AssetsAssigned");

                    b.Navigation("DepartmentsAsHead");

                    b.Navigation("MaintenanceRecordsReported");

                    b.Navigation("MaintenanceRecordsTechnician");

                    b.Navigation("PurchaseOrdersApproved");

                    b.Navigation("PurchaseOrdersCreated");

                    b.Navigation("SoftwareLicensesAssigned");

                    b.Navigation("Subordinates");

                    b.Navigation("TicketApprovals");

                    b.Navigation("TicketComments");

                    b.Navigation("TicketsAssigned");

                    b.Navigation("TicketsCreated");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.EmploymentStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Location", b =>
                {
                    b.Navigation("AssetAssignmentHistoriesFrom");

                    b.Navigation("AssetAssignmentHistoriesTo");

                    b.Navigation("Assets");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Modality", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.SoftwareLicense", b =>
                {
                    b.Navigation("LicenseAssignments");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Ticket", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("TicketApprovals");

                    b.Navigation("TicketComments");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CorporateAssetManager.Models.Vendor", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
